version: '3'
services: 
  test: 
    image: yoonhochoi231/mm-dev
    container_name: "mm-test"
    ports: 
    - "3000:3000"
    volumes: 
    - .:/usr/src/app
    - node_modules:/usr/src/app/node_modules
    command: npm run test
  
volumes:
  node_modules: {}